language: go
go:
- '1.10'
- master

go_import_path: github.com/ToDoist

script:
- go test -v
- go build
deploy:
  provider: heroku
  app: to-doist
  api_key:
    secure: dGhLvdkAEUD7yUqePkmVDoKLP+IRf+MdhWEETyCpCvCGzSjsPi/q+9Sv3W659nKJqK7Mec+m6Ms/nH8UNccS37jQkuNOlTB4I+ZsxVU7N/+hWBF/UfuG3bVEJkq9cSWVTErZjZ2fbMe4I4jR94qeBtSksev8eanyKa5MJfxUL22l8+NSlaVD1djVSBP9EqWx9BTNeCyWbS0mVGPYTP+TBzYuHOAJJ31ULKsT0exUfR6siiPQ1zBVy4igy/h824+Q4edX7r3cUSf33qtZlDsJ5vyAdN13+nfz3eyV3TiWYhXV4L3GaNIvpkzHrJW/r4XQj0XXMSAsspKwaGalln7Jzetd3jxe1sKtUGlTXpEf8ZZ845/4yVarsRHt8q5ei9imkg3eTn/MZ6D00dVLT0MB0Y70fmrOOw0gVh4yXIiXQm5+NQ+pGc3VXEBLlhdz6qUAwFoVaC9/6vbKmpGk1+rxbcjk/JAP7W8z4OSQnzbnLZfSCS/J7doyR3K5QzjuDOCkhd2qF+txMFFVg6zH7wM3/mVsl0e34U+A6SgKLDi5AJwuJWQLTBvuXa1YJETl5/sDq8lqZmYksQTE/dvzy1iUjF4mZ1U8NZyOlwQtnz9ZiQyC4OLuC+0s0gOU6KmYuAFvgqhcY0lAzq3/5iwXFlM6Y5hzMt6l1/l8dGdl4YaW7xI=
